apiVersion: v1
kind: Secret
metadata:
  name: api-riskmap-secret
data:
  DBUSER: $DB_USER_DEV
  DBHOST: $DB_HOST_DEV
  DBNAME: $DB_NAME
  MSSQL_TCP_PORT: $MSSQL_TCP_PORT_DEV
  MSSQL_SA_PASSWORD: $MSSQL_SA_PASSWORD_DEV

