FROM golang:1.19 AS builder

WORKDIR /app

ENV DIR_PROJ=backend

COPY ${DIR_PROJ}/go.mod .
COPY ${DIR_PROJ}/go.sum .
RUN go mod download

COPY ${DIR_PROJ}/. .
RUN go build -o /server

FROM gcr.io/distroless/base-debian10

COPY --from=builder /server /server

USER nonroot:nonroot

CMD [ "/server" ]