FROM golang:1.19.2-buster AS build

WORKDIR /app

ENV DIR_PROJ=backend

COPY ${DIR_PROJ}/go.mod .
COPY ${DIR_PROJ}/go.sum .
RUN go mod download

COPY ${DIR_PROJ}/. .
RUN go build -o server/

FROM gcr.io/distroless/base-debian10

WORKDIR /

COPY --from=build /app/server /server

ENTRYPOINT ["/server"]
