apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-riskmap
spec:
  selector:
    matchLabels:
      app: api-riskmap
  template:
    metadata:
      labels:
        app: api-riskmap
    spec:
      containers:
      - name: primary
        resources:
          limits:
            memory: 2000Mi
            cpu: 2
          requests:
            memory: 1024Mi
            cpu: 1





