### API Test
http://127.0.0.1:1234/

### SFLA API Test
POST  http://127.0.0.1:1234/SFLA
Content-Type: application/json

{
		"lat": "100.100",
		"long": "111.111",
		"i": 15.0,
		"date": "2021-11-1",
		"time": "15:15:44.123",
		"dev_id": "xxx",
		"type": "TR",
		"evDevice": "yyy",
		"PEA": "กฟฟ.ยโสธร",
		"PEA_code": "zzz",
		"typeFLT": 1
}

### MJM API Test
POST  http://127.0.0.1:1234/MJM
Content-Type: application/json

{
		"WORK_ID": 29467,
		"WORK_NAME": "RM_65_05_KTM_00001",
		"WORK_STATUS": "3",
		"AOJ_CODE": "0502501"
}

### RM API Test
POST  http://127.0.0.1:1234/RM
Content-Type: application/json

{
		"WORK_ID": 29467,
		"WORK_NAME": "RM_65_05_KTM_00001",
		"WORK_STATUS": "3",
		"AOJ_CODE": "0502501"
}

### API FE GET Test
http://127.0.0.1:1234/RM/NE2/กฟฟ.อุบลราชธานี/1


// SFLA Data
ID         int `gorm:"primaryKey"`
Latitude   string
Longtitude string
I          float64
Date       string
Time       string
DeviceID   string // feeder id
Type       string
EVDevice   string // equipment id
PEAName    string
PEACode    string
FaultType  int

// MJM Data
WorkName     string `gorm:"primaryKey"` // gen from riskmap
WorkType     string
WorkStatus   string
Customers    int // number of afected customers
DateFinished string

// Clustering Data
CenterX float64
CenterY float64
Radius  float64 // to be changed according to circle plotting requirement
Count   int
Archive bool

// RM data
Cluster   []Point
I         float64
Date      string
Type      string
EVDevice  string // equipment id
PEAName   string
FaultType int

WorkName     string // gen from riskmap
WorkType     string
WorkStatus   string // 0  = todo, 1 = doing, 2 = done
Customers    int    // number of afected customers
DateFinished string

CenterX float64
CenterY float64
Radius  float64 // to be changed according to circle plotting requirement
Count   int

PEAArea string